.catalog:
  name:  kong
  version: 2.1
  description:  kong
  kong-dashboard:
    scale: 1
    start_on_create: true
  postgres:
    scale: 1
    start_on_create: true
  kong:
    retain_ip: true
    scale: 1
    start_on_create: true
    health_check:
      healthy_threshold: 2
      response_timeout: 5000
      port: 8001
      unhealthy_threshold: 3
      interval: 5000
      strategy: recreate
      request_line: GET /# HTTP/1.0
